name: Bug Report
description: Create a bug report for Headless UI.
title: "[Bug]: "
labels: []
issue_body: true
body:
  - type: input
    attributes:
      label: What package within Headless UI are you using?
      description: 'For example: @headlessui/react'
    validations:
      required: true
  - type: input
    attributes:
      label: What version of that package are you using?
      description: 'For example: v0.3.1'
    validations:
      required: true
  - type: input
    attributes:
      label: What browser are you using?
      description: 'For example: Chrome, Safari, or N/A'
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction repository
      description: A public GitHub repo that demonstrates the bug. If it's really unnecessary, link us to a YouTube video you think is awesome instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your issue
      description: Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead
