blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/tailwindlabs/headlessui/discussions/new?category=ideas
    about: 'Suggest any ideas you have using our discussion forums.'
  - name: Help
    url: https://github.com/tailwindlabs/headlessui/discussions/new?category=help
    about: 'If you have a question or need help, ask a question on the discussion forums.'
  - name: Kind Words
    url: https://github.com/tailwindlabs/headlessui/discussions/new?category=kind-words
    about: "Have something nice to say about Headless UI or Tailwind in general? We'd love to hear it!"
